apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: elearning
type: Opaque
stringData:
  JWT_SECRET_KEY: "your-secret-key-change-in-production"
  POSTGRES_USER: "learning_user"
  POSTGRES_PASSWORD: "learning_password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  EMAIL_USER: "houssemmbarki615@gmail.com"
  EMAIL_PASSWORD: "bdajydfdkkngywrs"