apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: elearning
data:
  APP_NAME: "Learning Portal"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  NODE_ENV: "production"
  DEBUG: "false"
  COURSE_BACKEND_PORT: "8001"
  USER_BACKEND_PORT: "8002"
  ANALYTICS_BACKEND_PORT: "8003"
  AI_TUTOR_BACKEND_PORT: "8004"
  COURSE_SERVICE_URL: "http://course-service:8001"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8003"
  COURSE_BACKEND_URL: "http://course-service:8001"
  USER_BACKEND_URL: "http://user-service:8002"
  USER_BACKEND_ENV: "production"
  POSTGRES_DB: "learning_platform"
  POSTGRES_URL: "postgresql://learning_user:learning_password@postgres:5432/learning_platform"
  MONGODB_URI: "mongodb://mongo:27017/learning_platform"
  MONGO_INITDB_DATABASE: "learning_platform"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_TTL_SECONDS: "60"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET_NAME: "courses-media"
  MINIO_SECURE: "False"
  LLM_API_URL: "http://ollama:11434/v1"
  LLM_MODEL: "llama3"
  LLM_API_KEY: "ollama"
  N8N_FEEDBACK_WEBHOOK_URL: "http://n8n:5678/webhook-test/feedback"
  JWT_EXPIRE_TIME: "199d"
  JWT_ALGORITHM: "HS256"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "465"
  PUBLIC_FRONTEND_URL: "http://192.168.66.10"
  NEXT_PUBLIC_USER_SERVICE_URL: "http://192.168.66.10/api/v1/users"
  NEXT_PUBLIC_COURSE_SERVICE_URL: "http://192.168.66.10/api/v1"
  NEXT_PUBLIC_ANALYTICS_SERVICE_URL: "http://192.168.66.10/metrics"
  NEXT_PUBLIC_AI_TUTOR_SERVICE_URL: "http://192.168.66.10/api/v1/tutor"
  NEXT_PUBLIC_GATEWAY_URL: "http://192.168.66.10"