apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: elearning
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        upstream user_service      { server user-service:8002; }
        upstream course_service    { server course-service:8001; }
        upstream analytics_service { server analytics-service:8003; }
        upstream ai_tutor_service  { server ai-tutor-service:8004; }
        upstream learning_portal   { server learning-portal:3000; }

        server {
            listen 8000;

            location /api/v1/users {
                proxy_pass http://user_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /api/v1/courses {
                proxy_pass http://course_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /metrics {
                proxy_pass http://analytics_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /events {
                proxy_pass http://analytics_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /api/v1/tutor {
                proxy_pass http://ai_tutor_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location / {
                proxy_pass http://learning_portal;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }